QuanLyVeSo.Web/Areas/Admin/Controllers/CongNoController.cs
using QuanLyVeSo.Data.Dao;
using QuanLyVeSo.Data.EntityFramework;
using System.Web.Mvc;


namespace QuanLyVeSo.Web.Areas.Admin.Controllers
{
    public class CongNoController : Controller
    {
        // GET: Admin/CongNo

        public ActionResult Index(int? page, string query, string currentFilter)
        {
            if (query != null)
            {
                page = 1;
            }
            else
            {
                query = currentFilter;
            }

            ViewBag.CurrentFilter = query;
            var pageNumber = page ?? 1;
            var model = CongNoDao.Instance.ListPaged(pageNumber, query);
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CongNo entity)
        {
            if (ModelState.IsValid)
            {
                if (CongNoDao.Instance.Create(entity))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm mới công nợ không thành công");
                }
            }
            return View();
        }

        public ActionResult Detail(int id)
        {
            var model = CongNoDao.Instance.GetSingle(id);
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var model = CongNoDao.Instance.GetSingle(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CongNo model)
        {
            if (ModelState.IsValid)
            {
                if (CongNoDao.Instance.Update(model))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật đại lý không thành công");
                }
            }
            return View(model);
        }
        public ActionResult Delete(string id)
        {
            if (ModelState.IsValid)
            {
                if (CongNoDao.Instance.Delete(id))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Xóa công nợ không thành công");
                }
            }
            return View("Index");
        }

    }
}

QuanLyVeSo.Web/Areas/Admin/Controllers/GiaVeSoController.cs
using QuanLyVeSo.Data.Dao;
using QuanLyVeSo.Data.EntityFramework;
using System.Web.Mvc;

namespace QuanLyVeSo.Web.Areas.Admin.Controllers
{
    public class GiaVeSoController : Controller
    {
        // GET: Admin/GiaVeSo
        public ActionResult Index(int? page, string query, string currentFilter)
        {
            if (query != null)
            {
                page = 1;
            }
            else
            {
                query = currentFilter;
            }

            ViewBag.CurrentFilter = query;
            var pageNumber = page ?? 1;
            var model = GiaVeSoDao.Instance.ListPaged(pageNumber, query);
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(GiaVeSo entity)
        {
            if (ModelState.IsValid)
            {
                if (GiaVeSoDao.Instance.Create(entity))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm mới giá vé không thành công");
                }
            }
            return View();
        }


        public ActionResult Detail(int id)
        {
            var model = GiaVeSoDao.Instance.GetSingle(id);
            return View(model);
        }


        public JsonResult ChangeStatus(int id)
        {
            var result = GiaVeSoDao.Instance.ChangeStatus(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                if (GiaVeSoDao.Instance.Delete(id))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Xóa gía vé số không thành công");
                }
            }
            return View("Index");
        }

        public ActionResult Edit(int id)
        {
            var model = GiaVeSoDao.Instance.GetSingle(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(GiaVeSo model)
        {
            if (ModelState.IsValid)
            {
                if (GiaVeSoDao.Instance.Update(model))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật đại lý không thành công");
                }
            }
            return View(model);
        }

    }
}

QuanLyVeSo.Web/Areas/Admin/Views/GiaVeSo/Create.cshtml
@model QuanLyVeSo.Data.EntityFramework.GiaVeSo

@{
    ViewBag.Title = "Thêm mới giá vé";
}

@section header{
    <h1>Thêm mới giá vé</h1>
    
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin bài viết</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("Create", "GiaVeSo", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="box-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.MaGia)
                        @Html.TextBoxFor(model => model.MaGia, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaGia, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Gia)
                        @Html.TextBoxFor(model => model.Gia, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NgayBatDau)
                        @Html.TextBoxFor(model => model.NgayBatDau, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NgayKetThuc)
                        @Html.TextBoxFor(model => model.NgayKetThuc, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TrangThai)
                        <div class="checkbox">
                            <label>
                                @Html.CheckBoxFor(model => model.TrangThai)
                                Kích hoạt
                            </label>
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                    @Html.ActionLink("Hủy", "Index", new object { }, new { @class = "btn btn-default col-md-offset-1" })
                </div>
            }
        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/GiaVeSo/Detail.cshtml
@model QuanLyVeSo.Data.EntityFramework.CongNo

@{
    ViewBag.Title = "Thông tin công nợ";
}
@section header{
    <h1>Thông tin công nợ</h1>
    
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin bài viết</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <div class="box-body">

                <div class="form-group">
                    @Html.LabelFor(model => model.MaCongNo)
                    @Html.TextBoxFor(model => model.MaCongNo, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaDaiLy)
                    @Html.TextBoxFor(model => model.MaDaiLy, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SoTienBan)
                    @Html.TextBoxFor(model => model.SoTienBan, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HoaHong)
                    @Html.TextBoxFor(model => model.HoaHong, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgayNo)
                    @Html.TextBoxFor(model => model.NgayNo, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SoTienNo)
                    @Html.TextBoxFor(model => model.SoTienNo, new { @class = "form-control", @disabled = "disabled" })
                </div>

            </div>

            <!-- /.box-body -->
            <div class="box-footer">
                @Html.ActionLink("Về trang chủ", "Index", new object { }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/GiaVeSo/Edit.cshtml
@model QuanLyVeSo.Data.EntityFramework.CongNo

@{
    ViewBag.Title = "Cập nhật công nợ";
}
@section header{
    <h1>Cập nhật công nợ</h1>
   
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin đại lý</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("Edit", "CongNo", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="box-body">

                    @Html.HiddenFor(model => model.MaCongNo)

                    <div class="form-group">
                        @Html.LabelFor(model => model.MaDaiLy)
                        @Html.TextBoxFor(model => model.MaDaiLy, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SoTienBan)
                        @Html.TextBoxFor(model => model.SoTienBan, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SoTienBan, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.HoaHong)
                        @Html.TextBoxFor(model => model.HoaHong, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.HoaHong, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NgayNo)
                        @Html.TextBoxFor(model => model.NgayNo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.NgayNo, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SoTienNo)
                        @Html.TextBoxFor(model => model.SoTienNo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SoTienNo, "", new { @class = "text-danger" })
                    </div>
                
                </div>

                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                    @Html.ActionLink("Hủy", "Index", new object { }, new { @class = "btn btn-default col-md-offset-1" })
                </div>
            }
        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/GiaVeSo/Index.cshtml
@model PagedList.IPagedList<QuanLyVeSo.Data.EntityFramework.GiaVeSo>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Giá Vé";
}

@section header{
    <h1>Quản lý giá vé</h1>
    
}

@section scripts{
    <script src="~/Assets/Admin/js/controller/giavesocontroller.js"></script>
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            @using (Html.BeginForm("Index", "GiaVeSo", FormMethod.Get))
            {
                <div class="box-header">
                    <h3 class="box-title">Danh sách giá vé</h3>

                    <div class="box-tools pull-right">

                        <div class="input-group input-group-sm col-md-4 pull-right col-xs-offset-1">
                            @Html.TextBox("query", ViewBag.CurrentFilter as string, new { @class = "form-control pull-right", @placeholder = "Tìm kiếm" })
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                            </div>
                        </div>

                        <div class="pull-right">
                            <a href="/Admin/GiaVeSo/Create" class="btn btn-info btn-sm"> <i class="fa  fa-plus"></i> Thêm mới</a>
                        </div>
                    </div>
                </div>
            }

            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover table-bordered">
                    <tr>
                        <th>Giá</th>
                        <th>Ngày bắt đầu</th>
                        <th>Ngày kết thúc</th>
                        <th>Trạng thái</th>
                        <th>Chức năng</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaGia">
                            <td>@item.Gia</td>
                            <td>@item.NgayBatDau</td>
                            <td>@item.NgayKetThuc</td>
                            
                            <td>
                                <a href="#" data-id="@item.MaGia" class="@(item.TrangThai == true? "btn-change-status label label-success" : "btn-change-status label label-danger")">@(item.TrangThai ? "Kích hoạt" : "Khóa")</a>
                            </td>

                            <td>
                                @Html.ActionLink("Chi tiết", "Detail", new { ID = item.MaGia }) |
                                @Html.ActionLink("Sửa", "Edit", new { ID = item.MaGia }) |                      <a href="#" data-id="@item.MaGia" class="btn-delete">Xóa</a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <!-- /.box-body -->
            <!-- /.box-footer -->
        </div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của @Model.PageCount
    </div>
    <!-- /.box -->
</div>