QuanLyVeSo.Web/Areas/Admin/Controllers/PhieuPhatHanhController.cs
using QuanLyVeSo.Data.Dao;
using QuanLyVeSo.Data.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyVeSo.Web.Areas.Admin.Controllers
{
    public class PhieuPhatHanhController : Controller
    {
        // GET: Admin/PhieuPhatHanh
        public ActionResult Index(int? page, string query, string currentFilter)
        {
            if (query != null)
            {
                page = 1;
            }
            else
            {
                query = currentFilter;
            }

            ViewBag.CurrentFilter = query;
            var pageNumber = page ?? 1;
            var model = PhieuPhatHanhDao.Instance.ListPaged(pageNumber, query);
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(PhieuPhatHanh entity)
        {
            if (ModelState.IsValid)
            {
                if (PhieuPhatHanhDao.Instance.Create(entity))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm mới phiếu phát hành không thành công");
                }
            }
            return View();
        }
        public ActionResult Detail(string id)
        {
            var model = PhieuPhatHanhDao.Instance.GetSingle(id);
            return View(model);
        }
        public ActionResult Edit(string id)
        {
            var entity = PhieuPhatHanhDao.Instance.GetSingle(id);
            return View(entity);
        }
        [HttpPost]
        public ActionResult Edit(PhieuPhatHanh entity)
        {
            if (ModelState.IsValid)
            {
                if (PhieuPhatHanhDao.Instance.Update(entity))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật phiếu phát hành không thành công");
                }
            }
            return View(entity);
        }

        //public ActionResult Delete(string id)
        //{
        //    var entity = PhieuPhatHanhDao.Instance.GetSingle(id);
        //    return View(entity);
        //}
        public ActionResult Delete(string id)
        {
            //var entity = PhieuPhatHanhDao.Instance.GetSingle(id);
            if (ModelState.IsValid)
            {
                if (PhieuPhatHanhDao.Instance.Delete(id))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("","Xóa phiếu phát hành không thành công");
                }
            }
            return View("Index");
        }
        
    }
}

QuanLyVeSo.Web/Areas/Admin/Views/PhieuPhatHanh/Create.cshtml
@model QuanLyVeSo.Data.EntityFramework.PhieuPhatHanh

@{
    ViewBag.Title = "Thêm mới phiếu phát hành";
}

@section header{
    <h1>Thêm mới phiếu phát hành</h1>

}

<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin bài viết</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("Create", "PhieuPhatHanh", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="box-body">

                <div class="form-group">
                    @Html.LabelFor(model => model.MaPhieuPhatHanh)
                    @Html.TextBoxFor(model => model.MaPhieuPhatHanh, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaPhieuPhatHanh, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaDaiLy)
                    @Html.TextBoxFor(model => model.MaDaiLy, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgayPhatHanh)
                    @Html.TextBoxFor(model => model.NgayPhatHanh, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NgayPhatHanh, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TongSoLuongPhat)
                    @Html.TextBoxFor(model => model.TongSoLuongPhat, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TongSoLuongPhat, "", new { @class = "text-danger" })
                </div>
            </div>

                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                    @Html.ActionLink("Hủy", "Index", new object { }, new { @class = "btn btn-default col-md-offset-1" })
                </div>
            }
        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/PhieuPhatHanh/Detail.cshtml
@model QuanLyVeSo.Data.EntityFramework.PhieuPhatHanh

@{
    ViewBag.Title = "Thông tin chi tiết phiếu phát hành";
}
@section header{
<h1>Thông tin chi tiết phiếu phát hành</h1>
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin bài viết</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <div class="box-body">

                <div class="form-group">
                    @Html.LabelFor(model => model.MaPhieuPhatHanh)
                    @Html.TextBoxFor(model => model.MaPhieuPhatHanh, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaDaiLy)
                    @Html.TextBoxFor(model => model.MaDaiLy, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgayPhatHanh)
                    @Html.TextBoxFor(model => model.NgayPhatHanh, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TongSoLuongPhat)
                    @Html.TextBoxFor(model => model.TongSoLuongPhat, new { @class = "form-control", @disabled = "disabled" })
                </div>
            </div>

            <!-- /.box-body -->
            <div class="box-footer">
                @Html.ActionLink("Về trang chủ", "Index", new object { }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/PhieuPhatHanh/Edit.cshtml
@model QuanLyVeSo.Data.EntityFramework.PhieuPhatHanh

@{
    ViewBag.Title = "Cập nhật phiếu phát hành";
}
@section header{
<h1>Cập nhật phiếu phát hành</h1>

}

<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin phiếu phát hành</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("Edit", "PhieuPhatHanh", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="box-body">

                    @Html.HiddenFor(model => model.MaPhieuPhatHanh)

                    <div class="form-group">
                        @Html.LabelFor(model => model.MaPhieuPhatHanh)
                        @Html.TextBoxFor(model => model.MaPhieuPhatHanh, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaPhieuPhatHanh, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MaDaiLy)
                        @Html.TextBoxFor(model => model.MaDaiLy, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NgayPhatHanh)
                        @Html.TextBoxFor(model => model.NgayPhatHanh, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.NgayPhatHanh, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TongSoLuongPhat)
                        @Html.TextBoxFor(model => model.TongSoLuongPhat, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TongSoLuongPhat, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                    @Html.ActionLink("Hủy", "Index", new object { }, new { @class = "btn btn-default col-md-offset-1" })
                </div>
            }
        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/PhieuPhatHanh/Index.cshtml
@model PagedList.IPagedList<QuanLyVeSo.Data.EntityFramework.PhieuPhatHanh>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Phiếu phát hành";
}

@section header{
    Quản lý phiếu phát hành
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            @using (Html.BeginForm("Index", "PhieuPhatHanh", FormMethod.Get))
            {
                <div class="box-header">
                    <h3 class="box-title">Danh sách phiếu phát hành</h3>

                    <div class="box-tools pull-right">

                        <div class="input-group input-group-sm col-md-4 pull-right col-xs-offset-1">
                            @Html.TextBox("query", ViewBag.CurrentFilter as string, new { @class = "form-control pull-right", @placeholder = "Tìm kiếm" })
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                            </div>
                        </div>

                        <div class="pull-right">
                            <a href="/Admin/PhieuPhatHanh/Create" class="btn btn-info btn-sm"> <i class="fa  fa-plus"></i> Thêm mới</a>
                        </div>
                    </div>
                </div>
            }

            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover table-bordered">
                    <tr>
                        <th>Mã phiếu phát hành</th>
                        <th>Mã đại lý</th>
                        <th>Ngày phát hành</th>
                        <th>Tổng số lượng</th>
                        <th>Chức năng</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                    <tr id="row_@item.MaPhieuPhatHanh" class="">
                        <td>@item.MaPhieuPhatHanh</td>
                        <td>@item.MaDaiLy</td>
                        <td>@item.NgayPhatHanh</td>
                        <td>@item.TongSoLuongPhat</td>
                        <td>
                            @Html.ActionLink("Chi tiết", "Detail", new { ID = item.MaPhieuPhatHanh }) |
                            @Html.ActionLink("Sửa", "Edit", new { ID = item.MaPhieuPhatHanh }) |
                            @Html.ActionLink("Xóa", "Delete", new { id = item.MaPhieuPhatHanh })
                        </td>
                    </tr>
                    }
                </table>
            </div>
        </div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của @Model.PageCount
    </div>
    <!-- /.box -->
</div>