QuanLyVeSo.Web/Areas/Admin/Controllers/PhieuThuController.cs
using QuanLyVeSo.Data.Dao;
using QuanLyVeSo.Data.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyVeSo.Web.Areas.Admin.Controllers
{
    public class PhieuThuController : Controller
    {
        // GET: Admin/PhieuThu
        public ActionResult Index(int? page, string query, string currentFilter)
        {
            if (query != null)
            {
                page = 1;
            }
            else
            {
                query = currentFilter;
            }
            ViewBag.CurrentFilter = query;
            var pageNumber = page ?? 1;
            var model = PhieuThuDao.Instance.ListPaged(pageNumber, query);
            return View(model);
        }
        public ActionResult Create()
        {
            //ViewBag.MaDaiLy = new SelectList(DaiLyDao.Instance.AllDaiLys(), "MaDaiLy","TemDaiLy");
            //SelectList(IEnumberable,value cua option, cái hiển thị lên dropdown)
            ViewBag.MaDaiLy = new SelectList(DaiLyDao.Instance.AllDaiLys(), "MaDaiLy", "MaDaiLy");
            return View();
        }
        [HttpPost]
        public ActionResult Create(PhieuThu entity,FormCollection collection)
        {
            
            if (ModelState.IsValid)
            {
                entity.MaDaiLy = collection["TenDaiLy"].ToString();
                if (PhieuThuDao.Instance.Create(entity))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm mới phiếu thu không thành công");
                }
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            var model = PhieuThuDao.Instance.GetSingle(id);
            ViewBag.DanhSachMa = new SelectList(DaiLyDao.Instance.AllDaiLys(), "MaDaiLy", "MaDaiLy",model.MaDaiLy);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(PhieuThu entity,FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                entity.MaDaiLy = collection["TenList"].ToString();
                if (PhieuThuDao.Instance.Update(entity))
                {
                   return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật phiếu thu không thành công!");
                }
            }
            return View();
        }
        public ActionResult Detail(int id)
        {
            return View(PhieuThuDao.Instance.GetSingle(id));
        }
        public JsonResult Delete(int id)
        {
            var result = PhieuThuDao.Instance.Delete(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

QuanLyVeSo.Web/Areas/Admin/Views/PhieuThu/Create.cshtml
@model QuanLyVeSo.Data.EntityFramework.PhieuThu

@{
    ViewBag.Title = "Thêm mới phiếu thu";
}

@section header{
    Thêm mới phiếu thu
}
<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin bài viết</h3>
            </div>
            <!-- /.box-header -->
            @using (Html.BeginForm("Create", "PhieuThu", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.MaDaiLy)
                        @Html.DropDownList("TenDaiLy", (SelectList) ViewBag.MaDaiLy, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NgayThu)
                        @Html.TextBoxFor(model => model.NgayThu, new { @class = "form-control"  })
                        @Html.ValidationMessageFor(model => model.NgayThu, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TienThu)
                        @Html.TextBoxFor(model => model.TienThu, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TienThu, "", new { @class = "text-danger" })
                    </div>
                    
                </div>
                <!--End box-body-->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                    @Html.ActionLink("Hủy", "Index", new object { }, new { @class = "btn btn-default col-md-offset-1" })
                </div>
            }

        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/PhieuThu/Detail.cshtml
@model QuanLyVeSo.Data.EntityFramework.PhieuThu

@{
    ViewBag.Title = "Detail";
}

@section header{
    <h1>Thông tin phiếu thu</h1>
    <ol class="breadcrumb">
        <li><a href="/Admin"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="/Admin/PhieuThu">Phiếu thu</a></li>
        <li class="active">Chi tiết</li>
    </ol>
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin bài viết</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <div class="box-body">

                <div class="form-group">
                    @Html.LabelFor(model => model.MaPhieuThu)
                    @Html.TextBoxFor(model => model.MaPhieuThu, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaDaiLy)
                    @Html.TextBoxFor(model => model.MaDaiLy, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgayThu)
                    @Html.TextBoxFor(model => model.NgayThu, new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TienThu)
                    @Html.TextBoxFor(model => model.TienThu, new { @class = "form-control", @disabled = "disabled" })
                </div>
            </div>

            <!-- /.box-body -->
            <div class="box-footer">
                @Html.ActionLink("Về trang chủ", "Index", new object { }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/PhieuThu/Edit.cshtml
@model QuanLyVeSo.Data.EntityFramework.PhieuThu

@{
    ViewBag.Title = "Cập nhật phiếu thu";
}

@section header{
    <h1>Cập nhật phiếu thu</h1>
    <ol class="breadcrumb">
        <li><a href="/Admin"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="/Admin/PhieuThu">Phiếu thu</a></li>
        <li class="active">Cập nhật</li>
    </ol>
}
<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Thông tin đại lý</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="box-body">
                    @Html.HiddenFor(model => model.MaPhieuThu)

                    <div class="form-group">
                        @Html.LabelFor(model => model.MaDaiLy, new { @class = "control-label col-md-2" })
                        @Html.DropDownList("TenList", (SelectList)ViewBag.DanhSachMa, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NgayThu, new { @class = "control-label col-md-2" })
                        @Html.TextBoxFor(model => model.NgayThu, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.NgayThu, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TienThu, new { @class = "control-label col-md-2" })
                        @Html.TextBoxFor(model => model.TienThu, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TienThu, "", new { @class = "text-danger" })
                    </div>
                </div>
                <!--End box body-->
                <!--Begin box footer-->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                    @Html.ActionLink("Hủy", "Index", new object { }, new { @class = "btn btn-default col-md-offset-1" })
                </div>
            }
        </div>
    </div>
</div>

QuanLyVeSo.Web/Areas/Admin/Views/PhieuThu/Index.cshtml
@model PagedList.IPagedList<QuanLyVeSo.Data.EntityFramework.PhieuThu>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Phiếu thu";
}

@section header{
    Quản lý phiếu thu
}
    
    
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            @using (Html.BeginForm("Index", "PhieuThu", FormMethod.Get))
            {
                <div class="box-header">
                    <h3 class="box-title">Danh sách phiếu thu</h3>

                    <div class="box-tools pull-right">

                        <div class="input-group input-group-sm col-md-4 pull-right col-xs-offset-1">
                            @Html.TextBox("query", ViewBag.CurrentFilter as string, new { @class = "form-control pull-right", @placeholder = "Tìm kiếm" })
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                            </div>
                        </div>

                        <div class="pull-right">
                            <a href="/Admin/PhieuThu/Create" class="btn btn-info btn-sm"> <i class="fa  fa-plus"></i> Thêm mới</a>
                        </div>
                    </div>
                </div>
            }

            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover table-bordered">
                    <tr>
                        <th>Mã phiếu thu</th>
                        <th>Mã đại lý</th>
                        <th>Ngày thu</th>
                        <th>Tiền thu</th>
                        <th>Chức năng</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaPhieuThu" class="">
                            <td>@item.MaPhieuThu</td>
                            <td>@item.MaDaiLy</td>
                            <td>@item.NgayThu</td>
                            <td>@item.TienThu</td>
                            <td>
                                @Html.ActionLink("Chi tiết", "Detail", new { ID = item.MaPhieuThu }) |
                                @Html.ActionLink("Sửa", "Edit", new { ID = item.MaPhieuThu }) |
                                @Ajax.ActionLink("Xóa", "Delete", new { id = item.MaPhieuThu }, new AjaxOptions
                           {
                               HttpMethod = "Delete",
                               Confirm = "Bạn muốn xóa bài viết này?",
                               OnSuccess = "$('#row_" + @item.MaPhieuThu + "').remove()",
                           })
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <!-- /.box-body -->
            <!-- /.box-footer -->
        </div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của @Model.PageCount
    </div>
    <!-- /.box -->
</div>